[package]
name = "aionbot-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
futures = "0.3.30"
rayon = "1.10.0"
regex = "1.10.6"
serde_json = "1.0.128"
state = "0.6.0"
tokio = { version = "1.40.0", features = ["rt"] }
