[package]
name = "aionbot-adapter-onebot"
version = "0.1.0"
edition = "2021"

[dependencies]
aionbot-core = { version = "0.1.0", path = "../aionbot-core" }
anyhow = "1.0.89"
futures-util = "0.3.30"
tokio = "1.40.0"
tokio-tungstenite = "0.24.0"
