name: Code Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Code Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**"
          config: .cspell.json
          strict: true
          verbose: true
      - name: Cargo Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Rust Format Check
        run: cargo fmt --all -- --check
